Repository clubgamma/club-gamma-backend, pull requests merged in 2024-10, with the labels that each got.

#4 Added Rate limiting and Authentication to route /api/users/sync-prs
  CONTRIBUTING.md
  package-lock.json
  package.json
  src/api/users/index.js
  src/utils/Middlewares.js
Labels: level 2

#7 Fix the bug in /api/leaderboard/search
  CONTRIBUTING.md
  src/api/leaderboard/controller.js
Labels: bug, hacktoberfest-accepted

#9 Save githubId in name Field if name is Null During User Creation
  src/api/auth/controller.js
Labels: bug, hacktoberfest-accepted

#10 Filter support for Leaderboard API
  src/api/leaderboard/controller.js
  src/api/leaderboard/index.js
Labels: level 2, hacktoberfest-accepted

#11 Added /api/stats route to fetch stats dynamically
  src/api/stats/controller.js
  src/api/stats/index.js
  src/app.js
  src/router.js
Labels: level 2, hacktoberfest-accepted

#19 Improved the Readme.md file and made it look a lot better attractive and attractive
  README.md
Labels: documentation, hacktoberfest-accepted

#22 Create API Endpoint to Fetch Project Contributors
  bun.lockb
  src/api/projects/controller.js
  src/api/projects/index.js
  src/app.js
  src/router.js
Labels: level 2, hacktoberfest-accepted

#21 Fixes #17 : label tracking with webhook
  prisma/schema.prisma
  src/webhook/github.js
Labels: level 2, hacktoberfest-accepted

#24 changes in ranking system
  src/api/leaderboard/controller.js
Labels: bug, hacktoberfest-accepted

#29 Implement new API endpoint: Project-wise contributions for users
  src/api/users/controller.js
Labels: level 2, hacktoberfest-accepted

#33 Added Functionality of Thank-You mail
  src/api/users/controller.js
  src/scripts/thank-you-mail.js
  src/templates/thank-you.ejs
  src/utils/Mailer.js
Labels: level 3, hacktoberfest-accepted
